spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate:
#      更新或者创建数据表
      ddl-auto: update
#      在控制台显示sql
    show-sql: true